[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "reactive-lib/=lib/reactive-lib/src/"
]
test = "test"
script = "script"
evm_version = "paris"
via_ir = true
optimizer = true
# fs_permissions = [{ access = "read-write", path = "./" }]
# exclude = ["src/v2-advanced/**"]
    # tx_fee_cap = "10 ether"

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
polygon_amoy = "https://rpc-amoy.polygon.technology"
reactive = "https://kopli.rpc.reactive.network"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
polygon_amoy = { key = "${POLYGONSCAN_KEY}" }
reactive = { key = "${REACTIVE_SCAN_KEY}" }

[fmt]
line_length = 120
wrap_comments = true
